### ISSUE TITLE
Default parameters in MaltExtract leading missing output

### ISSUE THREAD

**Issue by ardasevkar** [NBISweden/aMeta#153]
Hi,
When comparing my previous mapping results -which seem to be authentic- with the aMETA output, I noticed that there were significantly fewer reads in each case. Upon further investigation into the aMETA outputs, I observed that the default parameters in MaltExtract may lead to missing data in the final output. The default settings and their functions are as follows:

**--destackingOff**: This option removes reads in situations where there is an overlapping sequence between them. Essentially, using this option significantly decreases the total number of assigned reads on the specified node. It results in a lower number of reads but achieves high genome coverage.

**--downSampOff:** I think this option was added to speed up the process. Essentially, it restricts the maximum number of assigned reads for a specified node to 10,000.

**--dupRemOff**: It removes PCR duplicates. While it is a good option, sometimes obtaining raw, unfiltered data can be preferable. I use my in-house script to remove PCR duplicates.

From my understanding, in the aMETA pipeline, MaltExtract is only running with the parameters below:
```
-i -f -o --reads --threads --matches --minPI 85.0 --maxReadLength 0 --minComp 0.0 --meganSummary -t
```
It appears that the three parameters I mentioned above are missing. It seems like there may need to be some modifications in the aMETA pipeline to include those parameters accordingly. Detailed information for MaltExtract parameters can be found in the [HOPS Github page](https://github.com/rhuebler/HOPS).

**Comment by ZoePochon** [comment]
Arda is right, I have been avoiding to use the fasta files generated by MaltExtract because they always seemed to have too few reads and these default parameters are the reason.

I have now investigated it for one taxid in two samples. 

Sample 1:
- Pipeline MaltExtract rule: 2521 defaults reads for the species
- MaltExtract command suggested by Arda: 3557
- Megan extract reads from species and lower nodes manually: 3557

Sample 2:
- Pipeline MaltExtract rule: 2521 defaults reads for the species: 6219
- MaltExtract command suggested by Arda: 81171
- Megan extract reads from species and lower nodes manually: 81171

In the second case, a tremendous amount of reads is lost and this reflects in the authentication plots that don't appear to have a similar amount of reads depending on the input file they use.

So I suggest we include: 
--destackingOff
--downSampOff
--dupRemOff
In the Maltextract command to allow the user to obtain all the reads for a species and do downstream analyses involving those reads.

**Comment by LeandroRitter** [comment]
Agreed, will be fixed in the next PR

**Comment by LeandroRitter** [comment]
Thank you @ardasevkar for your valuable input! We have added

--destackingOff
--downSampOff
--dupRemOff

to the MaltExtract command line in the latest PR.
