### ISSUE TITLE
mem_mb in FastQC rule should be changed

### ISSUE THREAD

**Issue by LeandroRitter** [NBISweden/aMeta#156]
Right now FasQC_Before/After_Trimming, the memory parameter is set to 1024 MB, which leads to this error message:

```
Memory value 10240 MB was outside the allowed range (100 - 10000) at /aMeta/.snakemake/conda/29408ff88243ec3671290557f41f37da_/bin/fastqc line 203.
logs/FASTQC_AFTER_TRIMMING/NW-17.log (END)
```

**Comment by ZoePochon** [comment]
Hey Freya!

The preliminary solution is to specify in your slurm file how much memory to use within the range of 100 to 10000 like this for example:
# Amount of threads per rule
set-threads:
  - FastQC_AfterTrimming=2
  - FastQC_BeforeTrimming=2
# Amount of resources per rule
set-resources:
  - FastQC_AfterTrimming:mem_mb=6000
  - FastQC_BeforeTrimming:mem_mb=6000
  
  If your running the snakemake pipeline and are stuck with this error, a good tip would be to run it with snakemake with the option --keep-going so that it doesn't stop the process at the first error but once there is nothing left to run. 
  
  Hope this helps!

**Comment by LeandroRitter** [comment]
Has been fixed centrally in the latest PR. Closing for now.
