### ISSUE TITLE
errors after cutadapt

### ISSUE THREAD

**Issue by Sevgi-k** [NBISweden/aMeta#174]
Hi, 
I installed aMeta after reading "Remote providers have been replaced" in the issues folder. Also, the test run worked without any errors. Right now, I am trying to run aMeta using the full nt database for one sample but I am getting errors after cutadapt trimming. Here is the log file:

Activating conda environment: /work/kaynar1/aMeta/.snakemake/conda/96dcd9900f71782aa6bfd6ab41ccd9eb
Activating conda environment: /work/kaynar1/aMeta/.snakemake/conda/9bec8250133a041528200979af38c4b3
Waiting at most 5 seconds for missing files.
MissingOutputException in line 1 of /work/kaynar1/aMeta/workflow/rules/krakenuniq.smk:
Job Missing files after 5 seconds:
results/KRAKENUNIQ/2A-12A-1-83-85_WD_4g/sequences.krakenuniq
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 9 completed successfully, but some output files are missing. 9
  File "/home/kaynar1/.conda/envs/aMeta/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 584, in handle_job_success
  File "/home/kaynar1/.conda/envs/aMeta/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 252, in handle_job_success
Removing output files of failed job KrakenUniq since they might be corrupted:
results/KRAKENUNIQ/2A-12A-1-83-85_WD_4g/krakenuniq.output
[Mon Aug 12 15:29:20 2024]
Error in rule Bowtie2_Alignment:
    jobid: 5
    output: results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam, results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam.bai
    log: logs/BOWTIE2/2A-12A-1-83-85_WD_4g.log (check log file(s) for error message)
    conda-env: /work/kaynar1/aMeta/.snakemake/conda/96dcd9900f71782aa6bfd6ab41ccd9eb
    shell:
        bowtie2 --large-index -x resources/library.fna --end-to-end --threads 10 --very-sensitive -U results/CUTADAPT_ADAPTER_TRIMMING/2A-12A-1-83-85_WD_4g.trimmed.fastq.gz > $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/AlignedToBowtie2DB.sam 2> logs/BOWTIE2/2A-12A-1-83-85_WD_4g.log;grep @ $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/AlignedToBowtie2DB.sam | awk '!seen[$2]++' > $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/header_nodups.txt;grep -v '^@' $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/AlignedToBowtie2DB.sam > $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/AlignedToBowtie2DB.noheader.sam;cat $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/header_nodups.txt $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/AlignedToBowtie2DB.noheader.sam > $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/AlignedToBowtie2DB.nodups.sam;samtools view -bS -q 1 -h -@ 10 $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/AlignedToBowtie2DB.nodups.sam | samtools sort - -@ 10 -o results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam;samtools index results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam;rm $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/header_nodups.txt;rm $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/AlignedToBowtie2DB.noheader.sam;rm $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/AlignedToBowtie2DB.nodups.sam;rm $(dirname results/BOWTIE2/2A-12A-1-83-85_WD_4g/AlignedToBowtie2DB.bam)/AlignedToBowtie2DB.sam;
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

Is there any advise?

**Comment by ZoePochon** [comment]
Dear @Sevgi-k, I'm sorry I have missed your message previously. I guess you might have already fixed these errors since then, but in case not:
Could you try rerunning the snakemake command with --latency-wait to see if there was a latency problem with regard to the krakenuniq error. 
Regarding the bowtie2 error, it just says that it exited with a non-zero exit code. Could you provide the log file for that bowtie2 run? It should be in the logs folder. Do you have a cluster log output as well for that bowtie2 job? This would help understand what went wrong.

**Comment by LeandroRitter** [comment]
@Sevgi-k we need to see the log-files for the failed KrakenUniq and Bowtie2 jobs to be more specific with advising you. I believe both failures have same origin. Do you have non-empty trimmed files in the results/CUTADAPT_ADAPTER_TRIMMING folder?

**Comment by LeandroRitter** [comment]
@Sevgi-k also, did the FastQC step work actually? I can see that you are using very complex naming of your files which sometimes confuses snakemake and leads to incorrect parsing of your file names. So I suspect you might have encountered problems even before the cutadapt step. We need more information in order to help you. Perhaps to avoid multiple overwriting you could just delete the whole "aMeta/results" directory and restart aMeta. Please post the error on your screen and log-file of the first job that failed. I will close this issue for now, as the issue seems to be related to malformed input files, but feel free to re-open it in case you have more information.
